#!/usr/bin/env python3

import os
import sys
import argparse
import subprocess

TOOLS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = os.path.dirname(TOOLS_DIR)

def is_target(path):
  return path.endswith(b".ts")


def main():
  description = "Run prettier over anabasis"
  parser = argparse.ArgumentParser(description=description)
  parser.add_argument("--check", action="store_true")
  args = parser.parse_args()

  output = subprocess.check_output([
    "git",
    "ls-tree",
    "-r",
    "HEAD",
    "--full-name",
    "-z",
    ROOT_DIR
  ])

  lines = output.split(b"\0")
  paths = [line.split(b"\t", 1)[1] for line in lines if line]
  paths = [path for path in paths if is_target(path)]

  cmd = ["pnpm", "-C", ROOT_DIR, "exec", "prettier", "--log-level", "warn"]
  if args.check:
    cmd.append("--check")
  else:
    cmd.append("--write")
  cmd.extend(paths)
  p = subprocess.run(cmd)
  return p.returncode


if __name__ == "__main__":
  sys.exit(main())


