#!/bin/bash
set -e

pnpm exec esbuild js/bundle.ts --bundle --minify --outdir=internal/static --log-level=warning --sourcemap
pnpm exec esbuild js/tests_bundle.ts --bundle --minify --outdir=internal/static --log-level=warning --sourcemap --format=esm --platform=node
pnpm exec tailwindcss --input css/main.css --output internal/static/bundle.css

pnpm exec tsc --noEmit
node internal/static/tests_bundle.js
go build ./cmd/mylar
go test ./...

